#!/usr/bin/env bash
# Installs nginx and set a default messasge
# port 80 as a default

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html
sudo service nginx start
